language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t douglasrosa16/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true douglasrosa16/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "reactjs"
  env: "Reactjs-env"
  bucket_name: "elasticbeanstalk-sa-east-1-950620642904"                
  bucket_path: "reactjs"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY